#Contains List of tests
test_featureRegressionUT = [
'saiQosEgressFlowPolicer',
'saiQosEgressFlowPolicer',
]

crm_featureRegressionUT = [
'saiCrmFdbStaticTest', #FIXME: ac5p
'saiCrmFdbDynamicTest_1',
'saiCrmFdbDynamicTest_2',
'saiCrmFdbDynamicTest_3',
'saiCrmAclTableTest',
'saiCrmAclCounter',
'saiCrmAclGroup',
'saiCrmAclTableEntry',
'saiCrmIpv4RouteTest',
'saiCrmIpv6RouteTest',
'saiCrmIpv4NHTest',
'saiCrmIpv4NHTest_1',
'saiCrmIpv6NHTest',
'saiCrmIpv6NHTest_1',
'saiCrmIpv4NeighborTest', #FIXME: ac5p
'saiCrmIpv6NeighborTest', #FIXME: ac5p
'saiCrmNHGroupTest',
'saiCrmNHGroupMemberTest',
'saiCrmFdbDynamicAgeOutTest',
]

fdb_featureRegressionUT = [
'saiFdbDynamicForward_I',
'saiFdbDynamicForward_II',
'saiFdbDynamicForward_III',
'saiFdbDynamicForwardNeg_IV',
'saiFdbStaticForward',
'saiFdbStaticForwardNeg',
'saiFdbSAInvalidBehavior',
'saiFdbSAiszeroBehavior',
'saiFdbDAisSABehavior',
'saiFdbAgingDynamic_I',
'saiFdbAgingDynamic_II',
'saiFdbAgingDynamic_III',
'saiFdbAgingStatic_I',
'saiFdbAgingStatic_II',
'saiFdbAgingStatic_III',
'saiFdbAgingStatic_IV',
'saiFdbAgingIpv4_I',
'saiFdbAgingIpv4_II',
'saiFdbAgingIpv4_III',
'saiFdbAgingIpv4_IV',
'saiFdbAgingIpv6_I',
'saiFdbAgingIpv6_II',
'saiFdbAgingIpv6_III',
'saiFdbAgingIpv6_IV',
#'saiFdbFloodAfterDelete', #todo
]

mtu_featureRegressionUT = [
'saiMtuConfigTest',
'saiMtuConfigTest_I',
'saiMtuConfigTest_II',
'saiMtuConfigProfileTest',
'saiMtuConfigProfileTest_I',
'saiMtuIpProfileTest',
'saiMtuIpProfileTest_I',
'saiMtuIpProfileTest_II',
'saiMtuIpProfileTest_III',
'saiMtuIpProfileTest_IV',
]

l3_featureRegressionUT = [
'saiL3VerifyRouteNhForwarding',
'saiL3VerifyRouteNeigbourDrop',
'saiL3VerifyRouteNhLagForwarding',
'saiL3VerifyRouteNhLagForwardingIngressLag',
'saiL3VerifyRouteNhVlanIntfForwarding',
'saiL3VerifyRouteNhVlanIntfForwardingIngressVlanIntf',
'saiL3VerifyV4RouteDrop', #FIXME: ac5p
'saiL3VerifyV4RouteTrap', #FIXME: ac5p
'saiL3VerifyV6RouteDrop',
'saiL3VerifyV6RouteNhForwarding',
'saiL3VerifyV6RouteTrap',
'saiL3NhVerifyNhCreation', #FIXME: ac5p
'saiL3NhVerifyV4NeighbourCreation', #FIXME: ac5p
'saiL3NhVerifyV4NhGroupCreation', #FIXME: ac5p
'saiL3NhVerifyV6NeighbourCreation', #FIXME: ac5p
'saiL3NhVerifyV6NhCreation', #FIXME: ac5p
'saiL3NhVerifyV6NhGroupCreation', #FIXME: ac5p
'saiL3VerifyV4NhGroupForwarding',
'saiL3VerifyV4NhGroupForwarding_pktaction',
'saiL3VerifyV4NhMemberRemoveReAdd', #FIXME: ac5p
'saiL3VerifyV6NhGroupForwarding',
'saiL3NhVerifyNhDeletion',
#'saiL3VerifyRouteNeigbourTrap',
'saiL3SipEqualToDipBehavior',
]

everflow_featureRegressionUT = [
'saiEverflowIpv4ErspanTest',
#'saiEverflowIpv6ErspanTest', #TODO:Enable after IPV6 support
'saiEverflowIpv4ErspanMultipleACLRuleTest',
'saiEverflowIpv4ErspanMultipleMirrorSessionTest_1',
'saiEverflowIpv4ErspanMultipleMirrorSessionTest_2',
#'saiEverflowIpv6ErspanMultipleMirrorSessionTest_1', #TODO:Enable after IPV6 support
#'saiEverflowIpv6ErspanMultipleMirrorSessionTest_2', #TODO:Enable after IPV6 support
#'saiEverflowErspanMultipleMirrorSessionTest_1', #TODO:Enable after IPV6 support
#'saiEverflowErspanMultipleMirrorSessionTest_2', #TODO:Enable after IPV6 support
'saiEverflowIPUpdateTest',
'saiEverflowMACUpdateTest',
'saiEverflowMonitorPortUpdateTest',
'saiEverflowCrmCountAclEntryTest',
'saiEverflowGreProtoTypeUpdateTest',
'saiEverflowTOSUpdateTest',
'saiEverflowTTLUpdateTest',
'saiEverflowPolicer',
'saiEverflowPolicer_I',
]
acl_featureRegressionUT = [
'saiIngrAclL4SrcPort',
'saiIngrAclL4DstPort',
'saiIngrAclLagL4SrcDst',
'saiIngrAclLagParallelLookup',
'saiIngrAclParallelLookup',
'saiIngrAclLagSipv4Dipv4',
'saiIngrAclSipv6Dipv6',
'saiIngrAclTcpFlags',
'saiEgrAclL4SrcDst',
'saiEgrAclLagL4SrcDst',
'saiEgrAclLagParallelLookup',
'saiEgrAclLagSipv4Dipv4',
'saiEgrAclLagSipv6Dipv6',
'saiEgrAclParallelLookup',
'saiEgrAclSipv4Dipv4',
'saiEgrAclSipv6Dipv6',
]

qos_featureRegressionUT = [
'saiQosBufferPool',
'saiQosIngressBufferProfile', #FIXME:ac5p
'saiQosEgressBufferProfile', #FIXME:ac5p
'saiQosPortShaper',
'saiQosQueueScheduler',
'saiQosWredProfile',
'saiQosDot1pToTcMap',
'saiQosDot1pToColorMap',
'saiQosDscpToTcMap',
'saiQosDscpToColorMap',
'saiQosTcDpToDot1pMap',
'saiQosTcDpToDscpMap',
'saiQosTcToQueueMap',
'saiQosPfcToQueueMap',
'saiQosSymmetricPfc',
'saiQosAsymmetricPfc',
'saiQosIngressPortPolicer_I',
'saiQosIngressPortPolicer_II',
'saiQosIngressPortPolicerUcStorm',
'saiQosIngressPortPolicerBcStorm',
'saiQosIngressPortPolicerMcStorm',
'saiQosIngressFlowPolicer',
'saiQosEgressFlowPolicer',
]

mac_featureRegressionUT = [
'saiMacLinkStatus',
'saiMacPortLoopbackEnable',
'saiMacPortStatus',
'saiMacRxMaxFrameLen',
'saiMacRxMaxFrameLen_I',
'saiMacRxMaxFrameLen_II',
'saiMacRxMaxFrameLen_III',
'saiMacRxMaxFrameLen_IV',
'saiMacRxMaxFrameLen_V',
'saiMacSetFecModeFC',
'saiMacSetFecModeRS',
]

misc_featureRegressionUT = [
'saiPortAttrAdminState',
'saiFdbCreateGetPktAction',
'saiFdbSetGetPktAction',
'saiL2FloodingBasicUt',
'saiL3BasicUTRouting_I',
'saiL3BasicUTRouting_II',
'saiL3BasicUTRouting_III'
]

featureRegressionUT = [
'saiCrmFdbStaticTest',
'saiCrmFdbDynamicTest_1',
'saiCrmFdbDynamicTest_2',
'saiCrmFdbDynamicTest_3',
'saiCrmAclTableTest',
'saiCrmAclCounter',
'saiCrmAclGroup',
'saiCrmAclTableEntry',
'saiCrmIpv4RouteTest',
'saiCrmIpv6RouteTest',
'saiCrmIpv4NHTest',
'saiCrmIpv4NHTest_1',
'saiCrmIpv6NHTest',
'saiCrmIpv6NHTest_1',
'saiCrmIpv4NeighborTest',
'saiCrmIpv6NeighborTest',
'saiCrmNHGroupTest',
'saiCrmNHGroupMemberTest',
'saiCrmFdbDynamicAgeOutTest',
'saiFdbDynamicForward_I',
'saiFdbDynamicForward_II',
'saiFdbDynamicForward_III',
'saiFdbDynamicForwardNeg_IV',
'saiFdbStaticForward',
'saiFdbStaticForwardNeg',
'saiFdbSAInvalidBehavior',
'saiFdbSAiszeroBehavior',
'saiFdbDAisSABehavior',
'saiFdbAgingDynamic_I',
'saiFdbAgingDynamic_II',
'saiFdbAgingDynamic_III',
'saiFdbAgingStatic_I',
'saiFdbAgingStatic_II',
'saiFdbAgingStatic_III',
'saiFdbAgingStatic_IV',
'saiFdbAgingIpv4_I',
'saiFdbAgingIpv4_II',
'saiFdbAgingIpv4_III',
'saiFdbAgingIpv4_IV',
'saiFdbAgingIpv6_I',
'saiFdbAgingIpv6_II',
'saiFdbAgingIpv6_III',
'saiFdbAgingIpv6_IV',
#'saiFdbFloodAfterDelete', #todo
'saiMtuConfigTest',
'saiMtuConfigTest_I',
'saiMtuConfigTest_II',
'saiMtuConfigProfileTest',
'saiMtuConfigProfileTest_I',
'saiMtuIpProfileTest',
'saiMtuIpProfileTest_I',
'saiMtuIpProfileTest_II',
'saiMtuIpProfileTest_III',
'saiMtuIpProfileTest_IV',
'saiL3VerifyRouteNhForwarding',
'saiL3VerifyRouteNeigbourDrop',
'saiL3VerifyRouteNhLagForwarding',
'saiL3VerifyRouteNhLagForwardingIngressLag',
'saiL3VerifyRouteNhVlanIntfForwarding',
'saiL3VerifyRouteNhVlanIntfForwardingIngressVlanIntf',
'saiL3VerifyV4RouteDrop',
'saiL3VerifyV4RouteTrap',
'saiL3VerifyV6RouteDrop',
'saiL3VerifyV6RouteNhForwarding',
'saiL3VerifyV6RouteTrap',
'saiL3NhVerifyNhCreation',
'saiL3NhVerifyV4NeighbourCreation',
'saiL3NhVerifyV4NhGroupCreation',
'saiL3NhVerifyV6NeighbourCreation',
'saiL3NhVerifyV6NhCreation',
'saiL3NhVerifyV6NhGroupCreation',
'saiL3VerifyV4NhGroupForwarding',
'saiL3VerifyV4NhGroupForwarding_pktaction',
'saiL3VerifyV4NhMemberRemoveReAdd',
'saiL3VerifyV6NhGroupForwarding',
'saiL3NhVerifyNhDeletion',
#'saiL3VerifyRouteNeigbourTrap',
'saiL3SipEqualToDipBehavior',
'saiEverflowIpv4ErspanTest',
#'saiEverflowIpv6ErspanTest', #TODO:Enable after IPV6 support
'saiEverflowIpv4ErspanMultipleACLRuleTest',
'saiEverflowIpv4ErspanMultipleMirrorSessionTest_1',
'saiEverflowIpv4ErspanMultipleMirrorSessionTest_2',
#'saiEverflowIpv6ErspanMultipleMirrorSessionTest_1', #TODO:Enable after IPV6 support
#'saiEverflowIpv6ErspanMultipleMirrorSessionTest_2', #TODO:Enable after IPV6 support
#'saiEverflowErspanMultipleMirrorSessionTest_1', #TODO:Enable after IPV6 support
#'saiEverflowErspanMultipleMirrorSessionTest_2', #TODO:Enable after IPV6 support
'saiEverflowIPUpdateTest',
'saiEverflowMACUpdateTest',
'saiEverflowMonitorPortUpdateTest',
'saiEverflowCrmCountAclEntryTest',
'saiEverflowGreProtoTypeUpdateTest',
'saiEverflowTOSUpdateTest',
'saiEverflowTTLUpdateTest',
'saiEverflowPolicer',
'saiEverflowPolicer_I',
'saiIngrAclL4SrcPort',
'saiIngrAclL4DstPort',
'saiIngrAclLagL4SrcDst',
'saiIngrAclLagParallelLookup',
'saiIngrAclParallelLookup',
'saiIngrAclLagSipv4Dipv4',
'saiIngrAclSipv6Dipv6',
'saiIngrAclTcpFlags',
'saiEgrAclL4SrcDst',
'saiEgrAclLagL4SrcDst',
'saiEgrAclLagParallelLookup',
'saiEgrAclLagSipv4Dipv4',
'saiEgrAclLagSipv6Dipv6',
'saiEgrAclParallelLookup',
'saiEgrAclSipv4Dipv4',
'saiEgrAclSipv6Dipv6',
'saiQosBufferPool',
'saiQosIngressBufferProfile',
'saiQosEgressBufferProfile',
'saiQosPortShaper',
'saiQosQueueScheduler',
'saiQosWredProfile',
'saiQosDot1pToTcMap',
'saiQosDot1pToColorMap',
'saiQosDscpToTcMap',
'saiQosDscpToColorMap',
'saiQosTcDpToDot1pMap',
'saiQosTcDpToDscpMap',
'saiQosTcToQueueMap',
'saiQosPfcToQueueMap',
'saiQosSymmetricPfc',
'saiQosAsymmetricPfc',
'saiQosIngressPortPolicer_I',
'saiQosIngressPortPolicer_II',
'saiQosIngressPortPolicerUcStorm',
'saiQosIngressPortPolicerBcStorm',
'saiQosIngressPortPolicerMcStorm',
'saiQosIngressFlowPolicer',
'saiQosEgressFlowPolicer',
'saiMacLinkStatus',
'saiMacPortLoopbackEnable',
'saiMacPortStatus',
'saiMacRxMaxFrameLen',
'saiMacRxMaxFrameLen_I',
'saiMacRxMaxFrameLen_II',
'saiMacRxMaxFrameLen_III',
'saiMacRxMaxFrameLen_IV',
'saiMacRxMaxFrameLen_V',
'saiMacSetFecModeFC',
'saiMacSetFecModeRS',
'saiPortAttrAdminState',
]


m0_featureRegressionUT = [
'saiCrmFdbStaticTest',
'saiCrmFdbDynamicTest_1',
'saiCrmFdbDynamicTest_2',
'saiCrmFdbDynamicTest_3',
'saiCrmAclTableTest',
'saiCrmAclCounter',
'saiCrmAclGroup',
'saiCrmAclTableEntry',
'saiCrmIpv4RouteTest',
'saiCrmIpv6RouteTest',
'saiCrmIpv4NHTest',
'saiCrmIpv4NHTest_1',
'saiCrmIpv6NHTest',
'saiCrmIpv6NHTest_1',
'saiCrmIpv4NeighborTest',
'saiCrmIpv6NeighborTest',
'saiCrmNHGroupTest',
'saiCrmNHGroupMemberTest',
'saiCrmFdbDynamicAgeOutTest',
'saiFdbDynamicForward_I', 
'saiFdbDynamicForward_II',
'saiFdbDynamicForward_III',
'saiFdbDynamicForwardNeg_IV',
'saiFdbStaticForward',
'saiFdbStaticForwardNeg',
'saiFdbSAInvalidBehavior',
'saiFdbSAiszeroBehavior',
'saiFdbDAisSABehavior',
'saiFdbAgingDynamic_I',
'saiFdbAgingDynamic_II',
'saiFdbAgingDynamic_III',
'saiFdbAgingStatic_I',
'saiFdbAgingStatic_II',
'saiFdbAgingStatic_III',
'saiFdbAgingStatic_IV',
'saiFdbAgingIpv4_I',
'saiFdbAgingIpv4_II',
'saiFdbAgingIpv4_III',
'saiFdbAgingIpv4_IV',
'saiFdbAgingIpv6_I',
'saiFdbAgingIpv6_II',
'saiFdbAgingIpv6_III',
'saiFdbAgingIpv6_IV',
#'saiFdbFloodAfterDelete', #todo
'saiMtuConfigTest',
'saiMtuConfigTest_I',
'saiMtuConfigTest_II',
'saiMtuConfigProfileTest',
'saiMtuConfigProfileTest_I',
'saiMtuIpProfileTest',
'saiMtuIpProfileTest_I',
'saiMtuIpProfileTest_II',
'saiMtuIpProfileTest_III',
'saiMtuIpProfileTest_IV',
'saiL3VerifyRouteNhForwarding',
'saiL3VerifyRouteNeigbourDrop',
'saiL3VerifyRouteNhLagForwarding',
'saiL3VerifyRouteNhLagForwardingIngressLag',
'saiL3VerifyRouteNhVlanIntfForwarding',
'saiL3VerifyRouteNhVlanIntfForwardingIngressVlanIntf',
'saiL3VerifyV4RouteDrop',
'saiL3VerifyV4RouteTrap',
'saiL3VerifyV6RouteDrop',
'saiL3VerifyV6RouteNhForwarding',
'saiL3VerifyV6RouteTrap',
'saiL3NhVerifyNhCreation',
'saiL3NhVerifyV4NeighbourCreation',
'saiL3NhVerifyV4NhGroupCreation',
'saiL3NhVerifyV6NeighbourCreation',
'saiL3NhVerifyV6NhCreation',
'saiL3NhVerifyV6NhGroupCreation',
'saiL3VerifyV4NhGroupForwarding',
'saiL3VerifyV4NhGroupForwarding_pktaction',
'saiL3VerifyV4NhMemberRemoveReAdd',
'saiL3VerifyV6NhGroupForwarding',
'saiL3NhVerifyNhDeletion',
#'saiL3VerifyRouteNeigbourTrap', #todo
'saiL3SipEqualToDipBehavior',
'saiEgrAclL4SrcDst',
'saiEgrAclLagL4SrcDst',
'saiEgrAclLagSipv6Dipv6',
'saiEgrAclLagSipv4Dipv4',
'saiEgrAclSipv6Dipv6',
'saiEgrAclSipv4Dipv4',
'saiIngrAclL4SrcPort',
'saiIngrAclL4DstPort',
'saiIngrAclLagL4SrcDst',
'saiIngrAclLagSipv4Dipv4',
'saiIngrAclSipv6Dipv6',
'saiIngrAclTcpFlags',
'saiMacRxMaxFrameLen',
'saiMacRxMaxFrameLen_I',
'saiMacRxMaxFrameLen_II',
'saiMacRxMaxFrameLen_III',
'saiMacRxMaxFrameLen_IV',
'saiMacRxMaxFrameLen_V',
]

